# Background and foreground colors
background = #000003
foreground = #ffeedb

# Standard colors
palette = 0=#000003
palette = 1=#f66d00
palette = 2=#b7ad00
palette = 3=#bbba00
palette = 4=#f97100
palette = 5=#fc7500
palette = 6=#c0af00
palette = 7=#ffeedb

# Bright colors
palette = 8=#5f6167
palette = 9=#ff8f00
palette = 10=#dbd400
palette = 11=#d8db00
palette = 12=#ff9300
palette = 13=#ff9700
palette = 14=#e3d300
palette = 15=#aeffe5
