$color = rgba(0, 0, 3, 1)
$inner_color = rgba(0, 0, 3, 0.66)
$outer_color = rgba(252, 117, 0, 1)
$font_color = rgba(255, 238, 219, 1)
$placeholder_color = rgba(255, 238, 219, 0.7)
$check_color = rgba(192, 175, 0, 1)
