background            #000003
foreground            #ffeedb

# black
color0  #000003
color8  #5f6167

# red
color1  #f66d00
color9  #ff8f00

# green
color2  #b7ad00
color10 #dbd400

# yellow
color3  #bbba00
color11 #d8db00

# blue
color4  #f97100
color12 #ff9300

# magenta
color5  #fc7500
color13 #ff9700

#cyan
color6  #c0af00
color14 #e3d300

#white
color7  #ffeedb
color15 #aeffe5


